name: Notify Slack on Claude Implementation Result

on:
  workflow_run:
    workflows: ["Claude Issue Implementation and Task Generation"]
    types: [completed]

jobs:
  slack_notify:
    runs-on: ubuntu-latest
    # Skip notifications for skipped/cancelled runs
    if: github.event.workflow_run.conclusion != 'cancelled' && github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Notify via Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Get workflow info
          WORKFLOW_ID="${{ github.event.workflow_run.id }}"
          WORKFLOW_URL="${{ github.event.workflow_run.html_url }}"
          REPOSITORY="${{ github.repository }}"
          CONCLUSION="${{ github.event.workflow_run.conclusion }}"
          ISSUE_NUMBER=$(echo "${{ github.event.workflow_run.head_commit.message }}" | grep -o '#[0-9]\+' | head -1 | tr -d '#' || echo "unknown")
          
          # Different messages for success and failure
          if [ "$CONCLUSION" == "success" ]; then
            EMOJI="✅"
            MESSAGE="Claude successfully completed implementation"
            COLOR="#36a64f"  # Green
          else
            EMOJI="❌"
            MESSAGE="Claude implementation failed"
            COLOR="#ff0000"  # Red
          fi
          
          # Generate issue URL if available
          if [ "$ISSUE_NUMBER" != "unknown" ]; then
            ISSUE_URL="https://github.com/$REPOSITORY/issues/$ISSUE_NUMBER"
            ISSUE_LINK="<$ISSUE_URL|Issue #$ISSUE_NUMBER>"
          else
            ISSUE_LINK="Unknown Issue"
          fi
          
          # Send to Slack
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [
                {
                  \"color\": \"$COLOR\",
                  \"blocks\": [
                    {
                      \"type\": \"section\",
                      \"text\": {
                        \"type\": \"mrkdwn\",
                        \"text\": \"$EMOJI *$MESSAGE*\\n$ISSUE_LINK | <$WORKFLOW_URL|View Workflow Run>\"
                      }
                    },
                    {
                      \"type\": \"context\",
                      \"elements\": [
                        {
                          \"type\": \"mrkdwn\",
                          \"text\": \"Repository: $REPOSITORY\"
                        }
                      ]
                    }
                  ]
                }
              ]
            }" \
            $SLACK_WEBHOOK_URL